name: Check for release
on:
  push:
    branches: 
      - "release/*.*.*"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
      - name: Check submodules status
        run: |
          git submodule update --remote
          if ! git diff --exit-code --quiet; then
            echo "submodule is not up to date"
            exit 1
          fi
      - name: Compile packages
        run: cargo build
      - name: Check crate version
        run: |
          tag=$(git describe --tags --abbrev=0)
          version=$(cargo run --bin crate_version)
          if [[ "$tag" == "$version" ]]; then
            echo 'Update crate version!'
            exit 1
          fi
