name: Check for release
on:
  pull_request:
    types:
      - opened
    branches: [ "release/0.0.0" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
      - name: Check submodules status
        run: |
          git submodule --remote
          if ! git diff --exit-code --quiet; then
            echo "submodule is not up to date"
            exit 1
          fi
      - name: Compile packages
        run: cargo build
      # DBG: debug step
      - name: Show cargo version
        run: cargo --version
