name: Release
on:
  push:
    branches:
      - "main"
jobs:
  push-tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
      - uses: arduino/setup-protoc@v1
      - uses: Swatinem/rust-cache@v2
      - name: Push tag when the latest tag and crate version are not same
        run: |
          tag=$(git describe --tags --abbrev=0)
          version=$(cargo run --bin crate_version)
          if [[ "$tag" != "$version" ]]; then
            git tag "$version"
            git push origin "$version"
          fi
