name: release
on:
  pull_request:
    types:
      - closed
    branches:
      - "release/*.*.*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
      - name: Test step
        run: cargo --version
